const headTables = [
  'Type Document',
  'Document Id',
  'First Surname',
  'Last Surname',
  'First Name',
  'Middle Name',
  'Email',
  'Phone',
  'Register Register',
  'Saber Pro score',
  'Saber Pro level',
  'Written Communication',
  'Written Communication Level',
  'Quantitative Reasoning',
  'Quantitative Reasoning Level',
  'Reading Critical',
  'Reading Critical Level',
  'Citizenship Competence',
  'Citizenship Competence Level',
  'English',
  'English Level',
  'EngineeringProject Formulation',
  'EngineeringProject FormulationLevel',
  'Mathematics Statistics',
  'Mathematics StatisticsLevel',
  'Software Design',
  'Software DesignLevel',
  'English Position',
  'Actions'
]

export default headTables
